version: '3'

services:
  nginx:
    build: ./nginx/
    container_name: nginx_server
    ports:
      - 80:80
      - 443:443
    
    links:
     - php
    
    volumes:
     - ./www/html/:/var/www/html

  php:
    build: ./php/
    container_name: php_container
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html/

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=galop_shop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1